---
title: Hello World
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: Kvirit1@hotmail.com
description: 'This is my firs site hosted on github.

'
baseurl: 
url: https://mariner-officers-47741.netlify.com
twitter_username: jekyllrb
github_username: Kvirit1
markdown: kramdown
